Break out fetching/installing a single package

diff --git a/src/jqnpm b/src/jqnpm
--- a/src/jqnpm
+++ b/src/jqnpm
@@ -113,6 +113,34 @@ function help {
 	echo "  execute     Run the current jq project."
 }
 
+function fetchSingle {
+	local dependencyName="$1"
+	shift
+
+	# TODO: use the semantic version and match against remote repo git tags.
+	dependencySemver=$(getDirectDependencyVersion "$dependencyName")
+
+	debug 4 "[$(getPackageName)] (installing) dependencyName '${dependencyName}'@'${dependencySemver}'"
+
+	# TODO: use a local folder per remote server, /github.com/?
+	# TODO REMOVE: using git bundles for now; use only for testing later.
+	local remote="${JQNPM_REMOTE_BASE:-config_default_remoteBase}/${dependencyName}.bundle"
+	local cache="${JQNPM_PACKAGES_CACHE:-config_default_packagesCache}/${dependencyName}"
+
+	if [[ ! -d "$cache" ]];
+	then
+		mkdir -p "$cache"
+	fi
+
+	# TODO: get list of local tags, match against it.
+	# TODO: get a list of remote tags.
+	# TODO: only download the best-matching tag, not the entire repository.
+	# TODO: use --bare repos, bundles or maybe zip files in cache?
+	# git clone --branch <tag> --single-branch --depth 1 "$remote" "$cache"
+	# TODO: fail gracefully if git fails.
+	git clone --single-branch --depth 1 "$remote" "$cache"
+}
+
 function fetch {
 	# Reads jq.json, clone remote repos to ./jq/packages/username/reponame
 	# This continues recursively.	
@@ -134,34 +162,42 @@ function fetch {
 
 	for dependencyName in "${directDependencyNames[@]}";
 	do
-		# TODO: use the semantic version and match against remote repo git tags.
-		dependencySemver=$(getDirectDependencyVersion "$dependencyName")
+		fetchSingle "$dependencyName"
 
-		debug 4 "[$(getPackageName)] (installing) dependencyName '${dependencyName}'@'${dependencySemver}'"
-
-		# TODO: use a local folder per remote server, /github.com/?
-		# TODO REMOVE: using git bundles for now; use only for testing later.
-		local remote="${JQNPM_REMOTE_BASE:-config_default_remoteBase}/${dependencyName}.bundle"
 		local cache="${JQNPM_PACKAGES_CACHE:-config_default_packagesCache}/${dependencyName}"
-
-		if [[ ! -d "$cache" ]];
-		then
-			mkdir -p "$cache"
-		fi
-
-		# TODO: get list of local tags, match against it.
-		# TODO: get a list of remote tags.
-		# TODO: only download the best-matching tag, not the entire repository.
-		# TODO: use --bare repos, bundles or maybe zip files in cache?
-		# git clone --branch <tag> --single-branch --depth 1 "$remote" "$cache"
-		# TODO: fail gracefully if git fails.
-		git clone --single-branch --depth 1 "$remote" "$cache"
 
 		# Fetch recursively.
 		pushd "$cache" >/dev/null
 		"$BASH_SOURCE" fetch
 		popd >/dev/null
 	done
+}
+
+function installSingle {
+	local dependencyName="$1"
+	shift
+
+	# TODO: use the semantic version and match against remote repo git tags.
+	dependencySemver=$(getDirectDependencyVersion "$dependencyName")
+
+	debug 4 "[$(getPackageName)] (installing) dependencyName '${dependencyName}'@'${dependencySemver}'"
+
+	# TODO: use a remote server, like github.
+	local remoteDependencyPath="${JQNPM_PACKAGES_CACHE}/${dependencyName}"
+	[[ ! -d "$remoteDependencyPath" ]] && die 1 "could not find the dependency '${dependencyName}' on the remote server."
+
+	# TODO: fix this lookup?
+	hasPackageMetadataFile || die 1 "the dependency '${dependencyName}' is missing '${packageMetadataFilename}'."
+
+	local localDependencyPath="$PWD/${localJqPackageBase}/${dependencyName}"
+
+	mkdir -p "$localDependencyPath"
+
+	# Use `git archive` to copy git content instead of the repository.
+	pushd "$remoteDependencyPath" >/dev/null
+	# TODO: use the right tag.
+	git archive HEAD | tar x -C "$localDependencyPath"
+	popd >/dev/null
 }
 
 function install {
@@ -195,27 +231,9 @@ function install {
 
 	for dependencyName in "${directDependencyNames[@]}";
 	do
-		# TODO: use the semantic version and match against remote repo git tags.
-		dependencySemver=$(getDirectDependencyVersion "$dependencyName")
-
-		debug 4 "[$(getPackageName)] (installing) dependencyName '${dependencyName}'@'${dependencySemver}'"
-
-		# TODO: use a remote server, like github.
-		local remoteDependencyPath="${JQNPM_PACKAGES_CACHE}/${dependencyName}"
-		[[ ! -d "$remoteDependencyPath" ]] && die 1 "could not find the dependency '${dependencyName}' on the remote server."
-
-		# TODO: fix this lookup?
-		hasPackageMetadataFile || die 1 "the dependency '${dependencyName}' is missing '${packageMetadataFilename}'."
+		installSingle "$dependencyName"
 
 		local localDependencyPath="$PWD/${localJqPackageBase}/${dependencyName}"
-
-		mkdir -p "$localDependencyPath"
-
-		# Use `git archive` to copy git content instead of the repository.
-		pushd "$remoteDependencyPath" >/dev/null
-		# TODO: use the right tag.
-		git archive HEAD | tar x -C "$localDependencyPath"
-		popd >/dev/null
 
 		# Install recursively.
 		pushd "$localDependencyPath" >/dev/null
